import AppKit
import Darwin
import Foundation

/// A macOS-created file or folder that does not belong on a volume shared with
/// another system.
///
/// Everything here is regenerated by macOS, which is why cleaning needs no
/// preview: the worst case is a rebuilt Spotlight index and a drive that
/// tidies itself again the next time the Mac browses it.
///
/// `.Trashes` is deliberately absent. It holds files the user deleted and may
/// still want back -- that is data, not clutter.
enum MacArtifact {
    case dsStore
    case appleDouble
    case extendedAttributes
    case spotlight
    case fileSystemEvents
    case temporaryItems
    case apDisk

    init?(name: String) {
        switch name {
        case ".DS_Store":       self = .dsStore
        case ".Spotlight-V100": self = .spotlight
        case ".fseventsd":      self = .fileSystemEvents
        case ".TemporaryItems": self = .temporaryItems
        // The marker macOS leaves on a volume it has connected. Matched by
        // exact name only: it shares no prefix with the `._*` sidecars below.
        case ".apdisk":         self = .apDisk
        // Sidecars sit next to media files; `@eaDir` is numbered (@eaDir1, ...).
        case _ where name.hasPrefix("._"):      self = .appleDouble
        case _ where name.hasPrefix("@eaDir"):  self = .extendedAttributes
        default:                                return nil
        }
    }

    /// Grouped-ordering for the log summary.
    static let allCases: [MacArtifact] = [
        .dsStore, .appleDouble, .extendedAttributes, .spotlight, .fileSystemEvents,
        .temporaryItems, .apDisk
    ]

    var summary: String {
        switch self {
        case .dsStore:            return ".DS_Store files"
        case .appleDouble:        return "._ AppleDouble files"
        case .extendedAttributes: return "@eaDir metadata folders"
        case .spotlight:          return "the Spotlight index"
        case .fileSystemEvents:   return "the file change journal"
        case .temporaryItems:     return "the temporary items folder"
        case .apDisk:             return ".apdisk volume markers"
        }
    }
}

struct CleanableItem {
    let url: URL
    let artifact: MacArtifact
    /// Entry names to leave in place inside a directory artefact.
    ///
    /// Empty for everything except a `.fseventsd` holding a `no_log` marker.
    /// See `preservedEntries(in:for:)`.
    let keeping: Set<String>
}

struct CleanResult {
    var removedPaths: [String] = []
    var failedPaths: [String] = []

    /// How many of each artefact type was removed, for the summary line.
    var removedByArtifact: [MacArtifact: Int] = [:]
    var wasCancelled = false

    var removedCount: Int { removedPaths.count }
    var failedCount: Int { failedPaths.count }
}

/// Removes macOS artefacts from a single volume.
///
/// Everything here blocks on the filesystem, so it only ever runs on a
/// background queue and never touches the main thread.
enum DiskCleaner {
    /// Cleaning is restricted to removable volumes, and never the startup disk.
    static func canClean(_ disk: DiskUsage) -> Bool {
        guard disk.isExternal else { return false }
        return disk.mountURL.standardizedFileURL.path != "/"
    }

    /// Walks the volume, then deletes what it found.
    ///
    /// Scanning first and deleting afterwards is what makes cancellation
    /// possible, and it means nothing is removed until the whole tree has been
    /// read.
    ///
    /// Returns `nil` if the volume was refused. The startup-volume check lives
    /// *here* and not only at the call site on purpose: this is the function
    /// that deletes files, and it must refuse `/` even if a future caller
    /// forgets to ask `canClean` first.
    static func clean(
        volume root: URL,
        progress: @escaping (Int) -> Void,
        isCancelled: @escaping () -> Bool
    ) -> CleanResult? {
        guard root.standardizedFileURL.path != "/" else { return nil }

        var result = CleanResult()
        let found = scan(root, progress: progress, isCancelled: isCancelled)

        if isCancelled() {
            result.wasCancelled = true
            return result
        }

        for item in found {
            do {
                try remove(item)
                result.removedPaths.append(item.url.path)
                result.removedByArtifact[item.artifact, default: 0] += 1
            } catch let error as NSError {
                // Already gone is the outcome we wanted, not a failure.
                //
                // On exFAT and FAT a file can carry its own AppleDouble sidecar:
                // a `.DS_Store` that has an extended attribute has a
                // `._.DS_Store` beside it, and both match this cleaner. Removing
                // the `.DS_Store` makes the kernel delete the sidecar as well,
                // so by the time the scan's own entry for `._.DS_Store` is
                // removed there is nothing there and FileManager reports
                // "“._.DS_Store” couldn't be removed." The volume came out
                // clean; only the count was wrong, and a run that reported
                // failures sent the user looking for a problem that was not
                // there. Counted as removed instead.
                if isAlreadyGone(error) {
                    result.removedPaths.append(item.url.path)
                    result.removedByArtifact[item.artifact, default: 0] += 1
                } else {
                    // A file we are not allowed to remove must not stop the run.
                    result.failedPaths.append("\(item.url.path) (\(error.localizedDescription))")
                }
            } catch {
                result.failedPaths.append("\(item.url.path) (\(error.localizedDescription))")
            }
        }

        return result
    }

    /// Whether an error from `FileManager` just means the item is not there.
    ///
    /// Two signals, checked in order of how much they can be trusted. The
    /// underlying POSIX code is authoritative — a missing file surfaces as
    /// `ENOENT` whatever the filesystem, and that is exactly the case a clean
    /// should shrug off. The Cocoa code is next: `removeItem` on a missing item
    /// reports `NSFileNoSuchFileError` (4) in `NSCocoaErrorDomain`, which is
    /// what exFAT produces here.
    ///
    /// Deliberately not matched on the localised text. "…couldn't be removed."
    /// is also what a permission failure looks like, and silently reclassifying
    /// a real failure as success would hide the one problem worth reporting.
    private static func isAlreadyGone(_ error: NSError) -> Bool {
        if let underlying = error.userInfo[NSUnderlyingErrorKey] as? NSError,
           underlying.domain == NSPOSIXErrorDomain,
           underlying.code == Int(ENOENT) {
            return true
        }

        return error.domain == NSCocoaErrorDomain && error.code == NSFileNoSuchFileError
    }

    /// Removes one scanned item, honouring anything it was told to keep.
    private static func remove(_ item: CleanableItem) throws {
        let manager = FileManager.default

        guard !item.keeping.isEmpty else {
            try manager.removeItem(at: item.url)
            return
        }

        // A directory with something to preserve: clear it out entry by entry
        // instead of deleting it, so the marker survives. Reached with
        // readdir rather than FileManager because `.fseventsd` is hidden.
        for name in directoryEntries(item.url).map(\.name) where !item.keeping.contains(name) {
            try manager.removeItem(at: item.url.appendingPathComponent(name))
        }
    }

    /// Markers inside an artefact directory that the cleaner must not remove.
    ///
    /// `.fseventsd/no_log` is put there on purpose: it tells macOS not to log
    /// file system events on the volume, which is how a drive gets prepared
    /// once and then cleaned repeatedly without the journal refilling. Taking
    /// the whole directory would take the marker with it, and macOS would
    /// recreate `.fseventsd` and start logging again on the very next mount.
    ///
    /// Checked per item rather than hard-coded, so a `.fseventsd` without the
    /// marker is still removed outright as before.
    private static func preservedEntries(in url: URL, for artifact: MacArtifact) -> Set<String> {
        // The only artefact that can hold one. Keeping this guard means the
        // extra readdir is not paid for every `._*` sidecar on the volume.
        guard artifact == .fileSystemEvents else { return [] }
        guard directoryEntries(url).contains(where: { $0.name == "no_log" }) else { return [] }
        return ["no_log"]
    }

    /// A directory entry paired with the type `readdir` reported for it.
    ///
    /// `d_type` arrives free with the directory read, so it can rule out a
    /// regular file without a syscall. Not every filesystem fills it in, hence
    /// `DT_UNKNOWN` and the fallback in `isTraversableDirectory(_:at:)`.
    private struct DirEntry {
        let name: String
        let type: UInt8
    }

    /// Whether the walk may descend into this entry.
    ///
    /// Two things are being rejected. A regular file cannot contain anything.
    /// And a symlink must never be followed, because `opendir` resolves one: a
    /// stray link on the volume pointing at a folder elsewhere on the Mac would
    /// otherwise pull the walk -- and the deletion -- clean outside the volume
    /// the user picked. Media drives accumulate exactly that kind of link.
    ///
    /// `d_type` settles both without touching the filesystem, which is the
    /// point on a volume holding hundreds of thousands of media files. The code
    /// this replaced pushed every entry onto the pending stack, so it `stat`ed
    /// each one and then called `opendir` on it -- a guaranteed-failing syscall
    /// for a regular file, spent on the large majority of entries in a library.
    ///
    /// A reported directory is still confirmed with `lstat`. Filesystem support
    /// for `d_type` is not something a cleaner this destructive should lean on
    /// for a safety guarantee, and confirming costs one syscall per directory
    /// rather than one per file. `lstat` reports on the link itself, so a link
    /// to a directory is still rejected.
    private static func isTraversableDirectory(_ entry: DirEntry, at url: URL) -> Bool {
        guard entry.type == UInt8(DT_UNKNOWN) || entry.type == UInt8(DT_DIR) else {
            return false
        }

        var info = stat()
        return url.withUnsafeFileSystemRepresentation { path in
            guard let path else { return false }
            return lstat(path, &info) == 0 && (info.st_mode & S_IFMT) == S_IFDIR
        }
    }

    /// Raw directory entries, including ones Foundation hides.
    ///
    /// `FileManager.contentsOfDirectory` filters out AppleDouble files: macOS
    /// flags `._*` as hidden, so the very files this feature exists to remove
    /// are invisible to it. POSIX `readdir` has no such filter, so the scan
    /// uses it directly.
    ///
    /// The type comes back alongside the name because it is free here and saves
    /// the round trips in `isTraversableDirectory(_:at:)`.
    private static func directoryEntries(_ url: URL) -> [DirEntry] {
        guard let dir = opendir(url.path) else { return [] }
        defer { closedir(dir) }

        var entries: [DirEntry] = []
        while let entry = readdir(dir) {
            // d_name is a fixed-size C array, so take the bytes up to the NUL.
            let name = withUnsafeBytes(of: entry.pointee.d_name) { raw -> String in
                String(decoding: raw.bindMemory(to: UInt8.self).prefix(while: { $0 != 0 }), as: UTF8.self)
            }

            if name == "." || name == ".." { continue }
            entries.append(DirEntry(name: name, type: entry.pointee.d_type))
        }

        return entries
    }

    private static func scan(
        _ root: URL,
        progress: (Int) -> Void,
        isCancelled: () -> Bool
    ) -> [CleanableItem] {
        var found: [CleanableItem] = []

        // An explicit walk rather than FileManager.enumerator: the enumerator
        // cannot be interrupted, and a multi-terabyte volume has to be
        // cancellable. Each directory is a bounded syscall we can check between.
        var pending: [URL] = [root]

        while let directory = pending.popLast() {
            if isCancelled() { return [] }

            for entry in directoryEntries(directory) {
                let name = entry.name
                let url = directory.appendingPathComponent(name)

                if let artifact = MacArtifact(name: name) {
                    found.append(CleanableItem(
                        url: url,
                        artifact: artifact,
                        keeping: preservedEntries(in: url, for: artifact)
                    ))
                    continue
                }

                // Don't descend into hidden or @-prefixed directories: no media
                // lives there, and .Spotlight-V100 in particular is enormous and
                // slow to walk. That also leaves .Trashes untouched for free.
                guard !name.hasPrefix("."), !name.hasPrefix("@") else { continue }

                // Regular files and symlinks are both rejected here. See
                // isTraversableDirectory for why neither may be walked.
                guard isTraversableDirectory(entry, at: url) else { continue }

                pending.append(url)
            }

            progress(found.count)
        }

        return found
    }

    // MARK: - Log

    /// `~/Library/Logs/DiskStat_clean.log` — the record of what was removed.
    static var logURL: URL {
        logDirectory.appendingPathComponent("DiskStat_clean.log", isDirectory: false)
    }

    /// Where the log lives.
    ///
    /// A `let` with a default rather than a `static var`, so it cannot be left
    /// redirected: a mutable global would be shared state, which is exactly what
    /// `-strict-concurrency` is here to reject, and it would be an error under
    /// the Swift 6 language mode. Overriding the log location is a test-only
    /// need, so the test passes its own directory in explicitly instead.
    static let logDirectory: URL = FileManager.default.homeDirectoryForCurrentUser
        .appendingPathComponent("Library/Logs", isDirectory: true)

    /// Appends a record of a clean. A big volume can list hundreds of thousands
    /// of paths, so the file is capped and restarted once it grows too large.
    ///
    /// `directory` defaults to the real log location and exists so a test can
    /// pass a temporary one. Parameterised rather than set through a mutable
    /// global, which would not be concurrency-safe.
    static func writeLog(
        disk: DiskUsage,
        result: CleanResult,
        directory: URL = logDirectory
    ) {
        let stamp = DateFormatter()
        stamp.dateFormat = "yyyy-MM-dd HH:mm:ss"

        var lines = [
            "[\(stamp.string(from: Date()))] Cleaned \(disk.name) (\(disk.path))"
        ]

        var summary = "Summary: removed=\(result.removedCount), failed=\(result.failedCount)"
        if result.wasCancelled { summary += " (cancelled)" }
        lines.append(summary)

        // Grouped by type first, so the useful part of the record survives even
        // if the cap below rolls the file over on a very large clean.
        if !result.removedByArtifact.isEmpty {
            lines.append("By type:")
            for artifact in MacArtifact.allCases where result.removedByArtifact[artifact] != nil {
                lines.append("  \(result.removedByArtifact[artifact] ?? 0) x \(artifact.summary)")
            }
        }

        lines.append("Removed items:")
        lines.append(contentsOf: result.removedPaths.sorted().map { "  \($0)" })

        if !result.failedPaths.isEmpty {
            lines.append("Failed items:")
            lines.append(contentsOf: result.failedPaths.sorted().map { "  \($0)" })
        }
        lines.append("")

        appendToLog(lines.joined(separator: "\n") + "\n", to: directory)
    }

    /// Removes the clean log, if there is one.
    ///
    /// No confirmation is asked for. The log is a convenience record — it is
    /// written again by the next clean — and a menu click on a deliberately
    /// worded item is intent enough. Returns whether anything was removed, so
    /// the caller can stay quiet when there was nothing to do.
    ///
    /// `directory` defaults to the real log location and exists so a test can
    /// pass a temporary one. Parameterised rather than set through a mutable
    /// global, for the same reason `writeLog` does it.
    @discardableResult
    static func clearLog(at directory: URL = logDirectory) -> Bool {
        let url = directory.appendingPathComponent("DiskStat_clean.log", isDirectory: false)
        guard FileManager.default.fileExists(atPath: url.path) else { return false }
        do {
            try FileManager.default.removeItem(at: url)
            return true
        } catch {
            return false
        }
    }

    private static func appendToLog(_ text: String, to directory: URL) {
        let url = directory.appendingPathComponent("DiskStat_clean.log", isDirectory: false)
        let manager = FileManager.default
        let data = Data(text.utf8)

        if let attributes = try? manager.attributesOfItem(atPath: url.path),
           let size = attributes[.size] as? NSNumber,
           size.int64Value > 1_000_000 {
            try? manager.removeItem(at: url)
        }

        if !manager.fileExists(atPath: url.path) {
            try? manager.createDirectory(
                at: url.deletingLastPathComponent(),
                withIntermediateDirectories: true
            )
        }

        if let handle = try? FileHandle(forWritingTo: url) {
            handle.seekToEndOfFile()
            handle.write(data)
            try? handle.close()
        } else {
            try? data.write(to: url)
        }
    }
}
