// Generated by scripts/set_version.sh -- do not edit.
//
// Regenerate after tagging:  ./scripts/set_version.sh
//
// The .app bundle reports CFBundleShortVersionString at runtime and this is
// only the fallback for running the binary directly.
let generatedVersion = "1.0.1"
