#!/usr/bin/env bash
# Writes the app version into a generated Swift file, so a bare `swift run`
# (which has no bundle to read CFBundleShortVersionString from) can still show
# the real number.
#
# This exists because Swift has no supported way to carry a *value* through a
# conditional compilation flag: `SwiftSetting.define` only turns a flag on or
# off, and the old `-D NAME="value"` form under `unsafeFlags` both warns and, as
# of Swift 6.4, never reaches `#if` at all.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT_FILE="$ROOT_DIR/Sources/diskstat/Version.swift"

if TAG="$(git -C "$ROOT_DIR" describe --tags --abbrev=0 2>/dev/null)"; then
    VERSION="${TAG#v}"
else
    VERSION="0.0.0-dev"
fi

NEW_CONTENT=$(cat <<SWIFT
// Generated by scripts/set_version.sh -- do not edit.
//
// Regenerate after tagging:  ./scripts/set_version.sh
//
// The .app bundle reports CFBundleShortVersionString at runtime and this is
// only the fallback for running the binary directly.
let generatedVersion = "${VERSION}"
SWIFT
)

# Only rewrite on a real change, so an ordinary build does not dirty the tree.
if [[ -f "$OUT_FILE" ]] && [[ "$(cat "$OUT_FILE")" == "$NEW_CONTENT" ]]; then
    echo "Version already ${VERSION}"
else
    printf '%s\n' "$NEW_CONTENT" > "$OUT_FILE"
    echo "Wrote version ${VERSION} to Sources/diskstat/Version.swift"
fi
